/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;


/**
 *
 * @author USER
 */
public class StartDashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */   
    public StartDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JButton();
        btnCashierLogin = new javax.swing.JButton();
        BG_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("FIND COMFORT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_toko-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 260, 140));

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        jLabel1.setText("BARUNO SHOE STORE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        btnAdminLogin.setBackground(new java.awt.Color(0, 0, 102));
        btnAdminLogin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnAdminLogin.setForeground(new java.awt.Color(0, 153, 153));
        btnAdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/person_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 190, 40));

        btnCashierLogin.setBackground(new java.awt.Color(0, 0, 102));
        btnCashierLogin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnCashierLogin.setForeground(new java.awt.Color(0, 153, 153));
        btnCashierLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/person_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnCashierLogin.setText("Cashier Login");
        btnCashierLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnCashierLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnCashierLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 190, 40));

        BG_Login.setForeground(new java.awt.Color(102, 153, 255));
        BG_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background_dashboard.png"))); // NOI18N
        getContentPane().add(BG_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        LoginAdmin loginAdm = new LoginAdmin();
        loginAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnCashierLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierLoginActionPerformed
        LoginCashier loginCsh = new LoginCashier();
        loginCsh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCashierLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Login;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnCashierLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
